BEGIN;

INSERT INTO subscription_plans (
  plan_name,
  plan_code,
  price_monthly,
  price_yearly,
  currency,
  max_listings,
  max_photos_per_listing,
  max_videos_per_listing,
  featured_listings_included,
  transaction_fee_percentage,
  priority_support,
  analytics_access,
  api_access,
  bulk_listing_tools,
  company_profile,
  badge_display,
  is_active,
  sort_order,
  description,
  features
) VALUES
  (
    'Free',
    'free',
    0.00,
    NULL,
    'XAF',
    1,
    5,
    0,
    0,
    5.00,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    NULL,
    TRUE,
    1,
    'Starter plan for casual sellers.',
    '["Basic listing","Email support","Standard verification"]'
  ),
  (
    'Basic',
    'basic',
    5000.00,
    50000.00,
    'XAF',
    3,
    10,
    0,
    0,
    4.50,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    'verified',
    TRUE,
    2,
    'Entry plan for growing sellers.',
    '["3 listings","Photo upgrades","Standard verification"]'
  ),
  (
    'Standard',
    'std',
    10000.00,
    100000.00,
    'XAF',
    6,
    15,
    1,
    1,
    4.00,
    TRUE,
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    'premium',
    TRUE,
    3,
    'Balanced plan for active sellers.',
    '["6 listings","1 video","Priority verification","Analytics"]'
  ),
  (
    'Professional',
    'pro',
    20000.00,
    200000.00,
    'XAF',
    12,
    20,
    3,
    3,
    3.50,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    'pro',
    TRUE,
    4,
    'Advanced plan for agencies and pros.',
    '["12 listings","3 videos","API access","Bulk tools"]'
  ),
  (
    'Enterprise',
    'ent',
    50000.00,
    500000.00,
    'XAF',
    25,
    50,
    5,
    5,
    3.00,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    'enterprise',
    TRUE,
    5,
    'Enterprise plan with full features.',
    '["25 listings","Dedicated support","Custom reporting"]'
  );

COMMIT;
